### ISSUE TITLE
Consistency error: No matching identifier val_ref found of type Field.

### ISSUE THREAD

**Issue by zgrannan** [viperproject/prusti-dev#359]
The following code is a minimized example of a larger program:

```rust
extern crate prusti_contracts;
use prusti_contracts::*;

#[pure]
#[trusted]
fn len(vec: &Vec<char>) -> usize {
    return vec.len();
}

#[pure]
#[trusted]
fn get_at(i: usize, vec: &Vec<String>) -> Vec<char> {
    return vec[i].chars().collect();
}

#[trusted]
#[ensures(forall(|i: usize| true ==> len(&get_at(i, &result)) > 1))]
fn get_lines() -> Vec<String> {
    return Vec::new();
}

#[trusted]
fn main() {}
```
And the result is:

```
~/o/r/a/three (master) prusti-rustc src/main.rs
  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 

{commit 22a4eb83 2021-01-18 13:24:14 UTC, built on 2021-01-20 21:02:47 UTC}


warning: function is never used: `get_lines`
  --> src/main.rs:18:4
   |
18 | fn get_lines() -> Vec<String> {
   |    ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

Verification of 4 items...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zgrannan/prusti-dev/viper_tools/backends/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zgrannan/prusti-dev/viper_tools/backends/silicon.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
error: [Prusti internal error] consistency error: Consistency error: No matching identifier val_ref found of type Field. (@0.0)

Verification failed
error: aborting due to previous error; 1 warning emitted

```

**Comment by vakaras** [comment]
The problem here is that the return type of a pure function must be `Copy`. This is clearly a regression caused by #354.

**Comment by Aurel300** [comment]
Prusti now correctly reports `return type of pure function does not implement Copy`. [`verify/fail/equality/pure-post-1.rs`](https://github.com/viperproject/prusti-dev/blob/b152e5a8786fce65dc34990ee50a9050b365f7f9/prusti-tests/tests/verify/fail/equality/pure-post-1.rs#L11)
